
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Nov 01 17:47:21 EDT 2011
//----------------------------------------------------

package fabric.tools.fabth;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 8;
  public static final int IDENT = 2;
  public static final int STRING_LITERAL = 3;
  public static final int EOF = 0;
  public static final int RBRACK = 7;
  public static final int COMMA = 11;
  public static final int error = 1;
  public static final int SEMICOLON = 10;
  public static final int RPAREN = 5;
  public static final int LBRACK = 6;
  public static final int RBRACE = 9;
  public static final int LPAREN = 4;
}

