package fabil;

/**
 * Version information for FabIL extension.
 *
 * DO NOT EDIT THIS CLASS BY HAND!  This is automatically generated by Ant.  If
 * you wish to change the version number, run one of the following:
 *
 *   ant bump-version  (Bumps the version number.)
 *   ant bump-major    (Bumps the major version number.)
 *   ant bump-minor    (Bumps the minor version number.)
 *   ant bump-patch    (Bumps the patch level.)
 */
public class Version extends polyglot.main.Version {
  @Override
  public String name() {
    return "fabil";
  }

  @Override
  public int major() {
    return 0;
  }

  @Override
  public int minor() {
    return 3;
  }

  @Override
  public int patch_level() {
    return 0;
  }

  @Override
  public String toString() {
    return "0.3.0 (2016-06-27 19:55:11 EDT)";
  }
}
